# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 583205f9324db1d1addb1821b47d03d038e8fbf65adee7b83fe726a2b2966a006f8802e4e58cc531b7b216a77f50f37f0503a816d610ac8b13d019a94ab3dfd8

test:
  secret_key_base: d3f9425948a2dec5ddc59ef1f3d37c5a8ec03ffc09d8440290c238fdbb9eb722ab724fcf6b01c3b1c428d643027ca87555001bf3e133c1c14548fc5f13557117

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
